@echo off
echo Starting AI Companion...

echo Starting Backend Server...
start "Backend" cmd /k "cd minimal-backend && node server.js"

echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul

echo Starting Web App...
start "Web App" cmd /k "cd minimal-web && npm run dev"

echo Both services are starting...
echo.
echo Web App: http://localhost:3000
echo Backend API: http://localhost:3001
echo.
echo Press any key to close this window...
pause > nul
